print("============Vetor Aluno==============")
aluno = []
print("Qual o nome do aluno?")
aluno.append(input())
print("Qual o curso do aluno?")
aluno.append(input())
print("Qual nota da AP1 do aluno?")
aluno.append(float(input()))
print("Qual nota da AP2 do aluno?")
aluno.append(float(input()))
aluno.append((aluno[2]+aluno[3])/2)    
print("==========================================")
print("Nome:",aluno[0])
print("Curso:",aluno[1])
print("AP1:",aluno[2])
print("AP2:",aluno[3])
print("Média:",aluno[4])